services:
  web:
    build:
      context: .
      dockerfile: dockerfilepro
    container_name: liv_pro
    command: >
      bash -c "python manage.py collectstatic --no-input &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn livflow.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
      - ./django:/app/django
      - /home/joo/back-end-coffee/django/logs:/home/joo/back-end-coffee/django/logs 
      - static_volume:/app/staticfiles
      - media_volume:/app/media  
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file: .env
    depends_on:
      - redis  # Redis 컨테이너가 먼저 실행되도록 설정

  nginx:
    image: nginx:alpine
    container_name: ng01
    ports:
      - "80:80"  # 80 포트 추가 (HTTP 인증용)
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot:/var/www/certbot  # Certbot 인증용 경로
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app-network


  db:
    image: postgres:latest
    container_name: db01
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=joo
      - POSTGRES_PASSWORD=livflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file: .env

  redis:
    image: redis:latest  
    container_name: redis01  # 컨테이너 이름 지정
    restart: always  # 컨테이너가 죽으면 자동 재시작
    ports:
      - "6379:6379"  # Redis 기본 포트
    networks:
      - app-network
    command: redis-server --appendonly yes  # 영구 저장 모드(AOF) 활성화
    env_file: .env

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  portainer_data:

networks:
  app-network:
    driver: bridge
