version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile  # 개발용 Dockerfile 사용
    container_name: liv_dev
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py createsuperuser &&
              python manage.py create_initial_data &&
              python manage.py create_dumy_data &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/app  # 로컬의 django 폴더를 컨테이너에 마운트
      - static_volume:/app/static
      - media_volume:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"  # Django의 디버그 모드 활성화
      DJANGO_SETTINGS_MODULE: "livflow.settings.base"  # 개발용 설정 파일 사용
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
