version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dockerfilepro
    container_name: liv_pro
    command: >
      bash -c "python manage.py collectstatic --no-input &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn livflow.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file: .env

  nginx:
    image: nginx:alpine
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Nginx가 직접 인증서를 참조
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app-network


  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt  # Nginx와 동일한 인증서 경로로 설정
  #     - ./data/certbot/www:/var/www/certbot  # Certbot 인증 경로
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  db:
    image: postgres:latest
    container_name: db01
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file: .env

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
