version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dockerfilepro
    container_name: liv_pro
    command: >
      bash -c "python manage.py collectstatic --no-input &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn livflow.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
      - ./django:/app/django
      - /home/joo/back-end-coffee/django/logs:/home/joo/back-end-coffee/django/logs 
      - static_volume:/app/django/static
      - media_volume:/app/django/media
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file: .env

  nginx:
    image: nginx:alpine
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db01
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=joo
      - POSTGRES_PASSWORD=livflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file: .env

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  portainer_data:

networks:
  app-network:
    driver: bridge
